spring:
  envTemp: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/spring_default?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    connectionTimeout: 30000
    minIdle: 10
    maxPoolSize: 50
    connectionInitSql: set names utf8mb4
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: ""
    timeout: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
  sleuth:
    enabled: true
    sampler:
      probability: 0.01
      rate: 10
mysql:
  jayDefaultName: jay_default
  jaydefault:
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_default_master?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      connectionTimeout: 30000
      minIdle: 10
      maxPoolSize: 50
      connectionInitSql: set names utf8mb4
  jayOneName: jay_one
  jayone:
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_one_master?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      connectionTimeout: 30000
      minIdle: 10
      maxPoolSize: 50
      connectionInitSql: set names utf8mb4
    slaves:
      - driverClassName: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_one_slave1?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        connectionTimeout: 30000
        minIdle: 10
        maxPoolSize: 50
        connectionInitSql: set names utf8mb4
      - driverClassName: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_one_slave2?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        connectionTimeout: 30000
        minIdle: 10
        maxPoolSize: 50
        connectionInitSql: set names utf8mb4
  jayTwoName: jay_two
  jaytwo:
    - master:
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_two_master1?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        connectionTimeout: 30000
        minIdle: 10
        maxPoolSize: 50
        connectionInitSql: set names utf8mb4
      slaves:
        - driverClassName: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_two_slave11?useUnicode=true&characterEncoding=utf8
          username: root
          password: 123456
          connectionTimeout: 30000
          minIdle: 10
          maxPoolSize: 50
          connectionInitSql: set names utf8mb4
        - driverClassName: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_two_slave12?useUnicode=true&characterEncoding=utf8
          username: root
          password: 123456
          connectionTimeout: 30000
          minIdle: 10
          maxPoolSize: 50
          connectionInitSql: set names utf8mb4
    - master:
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_two_master2?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        connectionTimeout: 30000
        minIdle: 10
        maxPoolSize: 50
        connectionInitSql: set names utf8mb4
      slaves:
        - driverClassName: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_two_slave21?useUnicode=true&characterEncoding=utf8
          username: root
          password: 123456
          connectionTimeout: 30000
          minIdle: 10
          maxPoolSize: 50
          connectionInitSql: set names utf8mb4
        - driverClassName: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_two_slave22?useUnicode=true&characterEncoding=utf8
          username: root
          password: 123456
          connectionTimeout: 30000
          minIdle: 10
          maxPoolSize: 50
          connectionInitSql: set names utf8mb4
  jayThreeName: jay_three
  jaythree:
    - master:
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_three_master1?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        connectionTimeout: 30000
        minIdle: 10
        maxPoolSize: 50
        connectionInitSql: set names utf8mb4
    - master:
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/jay_three_master2?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        connectionTimeout: 30000
        minIdle: 10
        maxPoolSize: 50
        connectionInitSql: set names utf8mb4
  shardingTables:
    user: 4


    #引用其他的yaml文件时
    #profiles:
    #include: yaml-test
