spring:
  profiles:
#    active: @activeProfile@
    active: dev
  application:
    name: practice-knowbox
server:
  port: 8081
eureka:
  client:
    enabled: false
    service-url: http://localhost:9090/eureka/
